box: wercker/default

build:
    steps:
      - pip install -r pip-requirements.txt --use-mirrors
      - pip install coveralls --use-mirrors
      - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
      - psql -c 'create database ejrf;' -U postgres
      - cp eJRF/travis-settings.py eJRF/localsettings.py
      - python manage.py syncdb --noinput
      - python manage.py migrate
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - coverage run manage.py test
      - python manage.py harvest

    after-steps:
      - coveralls