---
# tasks file for basic-setup
- apt: update_cache=yes cache_valid_time=3600

- apt: name={{item}} state=present
  with_items:
    - uwsgi
    - uwsgi-plugin-python

- template: src=ejrf.uwsgi.j2 dest=/etc/uwsgi/apps-available/ejrf.ini

- file: src=/etc/uwsgi/apps-available/ejrf.ini dest=/etc/uwsgi/apps-enabled/ejrf.ini state=link force=yes