---
- hosts: all
  sudo: yes
  tasks:
    - apt: name=git state=present update_cache=yes

    - apt: name={{ item }} state=present
      with_items:
        - python-pip
        - python-dev



    - pip: name={{ item }}
      with_items:
        - psycopg2
        - virtualenv

    - postgresql_user: name=ejrf password=ejrf
      sudo_user: postgres

    - name: pg_hba.conf localhost md5
      lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf regexp="^local[\s]+all[\s]+all[\s]+[\w]+$" line="local    all             all                                     md5"
      register: confchange

    - service: name=postgresql state=reloaded
      when: confchange|changed

    - command: ./postgresql reload
      when: confchange|changed
      args:
        chdir: /etc/init.d/

    - postgresql_db: name=ejrf owner=ejrf state=present
      sudo_user: postgres


    - file: path=/srv/checkout owner=ubuntu  mode=0755 state=directory

    - name: ejrf repo
      git: repo=https://github.com/eJRF/ejrf.git dest=/srv/checkout version=HEAD

    - name: ejrf requirements
      pip: requirements=/srv/checkout/pip-requirements.txt virtualenv=/srv/checkout/ejrfvenv

    - name: ejrf sync db
      script: sync-db.sh
      args:
        chdir: /srv/checko/

    - name: ejrf migrate d
      script: migrate-db.sh
      args:
        chdir: /srv/checkout/

    - name: copy service config
      copy: src=djangoservice.conf dest=/etc/init/djangoservice.conf

    - name: copy run server
      copy: src=run-server.sh dest=/srv/checkout/run-server.sh mode=777

    - name: start server
      script: start-server-initial.sh
