---
- hosts: all
  vars:
    version: "{{ lookup('env','SNAP_COMMIT') }}"
  tasks:

    - file: path=/srv/checkout owner=ubuntu  mode=0777
      sudo: yes

    - name: ejrf repo
      git: repo=https://github.com/eJRF/ejrf.git dest=/srv/checkout version="{{ version }}"

    - name: ejrf requirements
      pip: requirements=/srv/checkout/pip-requirements.txt virtualenv=/srv/checkout/ejrfvenv

#initial config
    - pip: name=psycopg2
      sudo: yes

#inital config
    - postgresql_db: name=ejrf owner=ejrf state=present login_user=ejrf login_password=ejrf
      sudo: yes

#initial config
    - name: ejrf sync db
      script: sync-db.sh
      args:
        chdir: /srv/checkout/

    - name: ejrf migrate db
      script: migrate-db.sh
      args:
        chdir: /srv/checkout/

    - name: copy service config
      copy: src=djangoservice.conf dest=/etc/init/djangoservice.conf
      sudo: yes

    - name: copy run server
      copy: src=run-server.sh dest=/srv/checkout/run-server.sh mode=777

    - name: start server
      script: start-server2.sh
